# params are from https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_navigation/param/dwa_local_planner_params_waffle_pi.yaml
DwaLocalPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.28
  min_vel_x: -0.28

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans: 0.28
  min_vel_trans: 0.13

  max_vel_theta: 1.82
  min_vel_theta: 0.9

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

# Goal Tolerance Parametes
  sim_time: 2.0
  controller_frequency: 10.0

# Trajectory Scoring Parameters
