robot_base_frame: $(arg frame)base_footprint

footprint:
  [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.105

inscribed_radius: 0.267
circumscribed_radius: 0.267

observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)base_scan,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }
